# Generated by Django 2.2.6 on 2019-10-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macros',
            name='comment',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='macros',
            name='description',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
