# Generated by Django 2.2.6 on 2019-10-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20191028_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='macros',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
